version: '3.7'
services:
  webapp:
    container_name: webapp
    build:
      context: .
      target: development
    image: webapp:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/gopath/src/project
